<a href="https://colab.research.google.com/github/Prajkta11222/Smart-Vehical-Health-Intelligence-and-Predictive-Maintenance-Recommendation-System/blob/main/Vehicle_Health_Model_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



Devlopment of a smart Vehical Health Intelligence and Predictive Maintenance Recommendation System

In [1]:
#Install Libraries
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [7]:
#Import Libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("ignore")

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
#Used later to divide data into training and testing sets.
from sklearn.model_selection import train_test_split
#Converts text labels into numeric values.
from sklearn.preprocessing import LabelEncoder
#Scales numerical features when required.
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

In [14]:
#upload dataset
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [15]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Smart_Vehicle_Health_Project/dataset/engine_data.csv')

In [16]:
df.head()

,Engine rpm,Lub oil pressure,Fuel pressure,Coolant pressure,lub oil temp,Coolant temp,Engine Condition
0,700,2.493592,11.790927,3.178981,84.144163,81.632187,1
1,876,2.941606,16.193866,2.464504,77.640934,82.445724,0
2,520,2.961746,6.553147,1.064347,77.752266,79.645777,1
3,473,3.707835,19.510172,3.727455,74.129907,71.774629,1
4,619,5.672919,15.738871,2.052251,78.396989,87.000225,0

In [17]:
df.shape

(19535, 7)

In [18]:
df.columns

Index(['Engine rpm', 'Lub oil pressure', 'Fuel pressure', 'Coolant pressure',
       'lub oil temp', 'Coolant temp', 'Engine Condition'],
      dtype='object')

In [19]:
df.dtypes

Engine rpm            int64
Lub oil pressure    float64
Fuel pressure       float64
Coolant pressure    float64
lub oil temp        float64
Coolant temp        float64
Engine Condition      int64
dtype: object