<a href="https://colab.research.google.com/github/Prajkta11222/Smart-Vehical-Health-Intelligence-and-Predictive-Maintenance-Recommendation-System/blob/main/Vehical_maintence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---
#Smart-Vehical-Health-Intelligence-and-Predictive-Maintenance-Recommendation-System


---

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:

# =============================================================================
# Dataset Path
# =============================================================================

DATASET_PATH = "/content/drive/MyDrive/Btech Final Year Project/Dataset/flex_fuel_predictive_maintenance_dataset_augmented.csv"

# =============================================================================
# Load Dataset
# =============================================================================

from pathlib import Path
import pandas as pd

# Check whether the dataset exists
if not Path(DATASET_PATH).exists():
    raise FileNotFoundError(
        f"Dataset not found.\nPlease check the path:\n{DATASET_PATH}"
    )

# Load dataset
vehicle_df = pd.read_csv(DATASET_PATH)

# Check if dataset is empty
if vehicle_df.empty:
    raise ValueError("The dataset is empty.")

print("✅ Dataset loaded successfully.")
print(f"Shape : {vehicle_df.shape}")

# Display first 5 rows
display(vehicle_df.head())

✅ Dataset loaded successfully.
Shape : (120000, 56)

,Vehicle_ID,Timestamp,Vehicle_Model,Vehicle_Age_years,Engine_Size_cc,Fuel_System_Material_Compatibility,Climate_Region,Ambient_Temperature_C,Humidity_Pct,Altitude_m,...,Fuel_Line_Seal_Condition,O2_Sensor_Response_ms,Cold_Start_Duration_s,Cranking_Voltage_V,Time_Since_Last_Service_days,Time_Since_Injector_Replacement_km,Time_Since_SparkPlug_Replacement_km,Need_Maintenance,Failure_Type,Remaining_Useful_Life_km
0,FFV2-000001,2023-07-04,Truck,10,2876,Standard,Coastal,22.3,73.3,394.0,...,Pass,151.0,1.47,11.70,19.0,140675.0,19822.0,Yes,Catalytic Converter,5383.0
1,FFV2-000002,2024-08-21,SUV,8,1935,Retrofit-Upgraded,Arid,22.7,29.3,629.0,...,Pass,140.0,1.74,11.79,93.0,158999.0,13537.0,Yes,Electrical,4120.0
2,FFV2-000003,2024-02-28,Truck,3,2964,Ethanol-Compatible (Tier-2/3),Arid,35.5,21.6,1538.0,...,Pass,96.0,1.47,12.10,221.0,51807.0,22730.0,No,No Failure,15566.0
3,FFV2-000004,2024-02-09,SUV,10,1945,Standard,Humid,23.8,78.2,391.0,...,Pass,129.0,1.67,NaN,23.0,121717.0,50980.0,Yes,Fuel System,3256.0
4,FFV2-000005,2024-05-16,Car,10,1125,Standard,Arid,40.5,28.0,NaN,...,Pass,160.0,1.86,11.80,195.0,3064.0,84.0,Yes,Injector,1037.0

In [15]:
# =============================================================================
# Stage 1 – Dataset Inspection
# Member 1
# =============================================================================

print("=" * 80)
print("SMART VEHICLE HEALTH INTELLIGENCE")
print("Stage 1 – Dataset Inspection")
print("=" * 80)

import pandas as pd
import numpy as np

# =============================================================================
# 1. Dataset Shape
# =============================================================================

print("\n" + "=" * 80)
print("1. DATASET SHAPE")
print("=" * 80)

print(f"Rows    : {vehicle_df.shape[0]:,}")
print(f"Columns : {vehicle_df.shape[1]}")

# =============================================================================
# 2. First Five Records
# =============================================================================

print("\n" + "=" * 80)
print("2. FIRST FIVE RECORDS")
print("=" * 80)

display(vehicle_df.head())

# =============================================================================
# 3. Dataset Information
# =============================================================================

print("\n" + "=" * 80)
print("3. DATASET INFORMATION")
print("=" * 80)

vehicle_df.info()

# =============================================================================
# 4. Data Types
# =============================================================================

print("\n" + "=" * 80)
print("4. DATA TYPES")
print("=" * 80)

display(vehicle_df.dtypes.to_frame(name="Data Type"))

# =============================================================================
# 5. Missing Value Analysis
# =============================================================================

print("\n" + "=" * 80)
print("5. MISSING VALUE ANALYSIS")
print("=" * 80)

missing = pd.DataFrame({
    "Missing Values": vehicle_df.isnull().sum(),
    "Missing Percentage (%)":
    (vehicle_df.isnull().mean()*100).round(2)
})

missing = missing[missing["Missing Values"] > 0]

if missing.empty:
    print("No missing values found.")
else:
    display(
        missing.sort_values(
            by="Missing Percentage (%)",
            ascending=False
        )
    )

# =============================================================================
# 6. Duplicate Analysis
# =============================================================================

print("\n" + "=" * 80)
print("6. DUPLICATE ANALYSIS")
print("=" * 80)

duplicates = vehicle_df.duplicated().sum()

print(f"Duplicate Rows : {duplicates:,}")

# =============================================================================
# 7. Statistical Summary
# =============================================================================

print("\n" + "=" * 80)
print("7. NUMERICAL FEATURE SUMMARY")
print("=" * 80)

display(vehicle_df.describe())

# =============================================================================
# 8. Target Variable Analysis
# =============================================================================

print("\n" + "=" * 80)
print("8. TARGET VARIABLE ANALYSIS")
print("=" * 80)

# -------------------------------------------------------------------------
# Primary Target
# -------------------------------------------------------------------------

print("\nNeed_Maintenance Distribution\n")

display(vehicle_df["Need_Maintenance"].value_counts())

print("\nPercentage Distribution\n")

display(
    (
        vehicle_df["Need_Maintenance"]
        .value_counts(normalize=True)*100
    ).round(2)
)

# -------------------------------------------------------------------------
# Secondary Target
# -------------------------------------------------------------------------

print("\nFailure_Type Distribution\n")

display(vehicle_df["Failure_Type"].value_counts())

# -------------------------------------------------------------------------
# Remaining Useful Life
# -------------------------------------------------------------------------

print("\nRemaining_Useful_Life_km Summary\n")

display(vehicle_df["Remaining_Useful_Life_km"].describe())

# =============================================================================
# 9. Dataset Quality Summary
# =============================================================================

print("\n" + "=" * 80)
print("9. DATASET QUALITY SUMMARY")
print("=" * 80)

print(f"Total Features          : {vehicle_df.shape[1]}")
print(f"Total Records           : {vehicle_df.shape[0]:,}")
print(f"Missing Values          : {vehicle_df.isnull().sum().sum():,}")
print(f"Duplicate Rows          : {duplicates:,}")

numeric = vehicle_df.select_dtypes(include=np.number).shape[1]
categorical = vehicle_df.select_dtypes(
    include=["object", "category", "bool"]
).shape[1]

print(f"Numeric Features        : {numeric}")
print(f"Categorical Features    : {categorical}")

# =============================================================================
# 10. Observations
# =============================================================================

print("\n" + "=" * 80)
print("10. OBSERVATIONS")
print("=" * 80)

print("• Dataset loaded successfully.")
print("• Dataset structure verified.")
print("• Data types inspected.")
print("• Missing values identified.")
print("• Duplicate rows checked.")
print("• Target variables verified.")
print("• Dataset remains unchanged.")
print("• Dataset is ready for Stage 2 (Exploratory Data Analysis).")

================================================================================
SMART VEHICLE HEALTH INTELLIGENCE
Stage 1 – Dataset Inspection
================================================================================

================================================================================
1. DATASET SHAPE
================================================================================
Rows    : 120,000
Columns : 56

================================================================================
2. FIRST FIVE RECORDS
================================================================================

,Vehicle_ID,Timestamp,Vehicle_Model,Vehicle_Age_years,Engine_Size_cc,Fuel_System_Material_Compatibility,Climate_Region,Ambient_Temperature_C,Humidity_Pct,Altitude_m,...,Fuel_Line_Seal_Condition,O2_Sensor_Response_ms,Cold_Start_Duration_s,Cranking_Voltage_V,Time_Since_Last_Service_days,Time_Since_Injector_Replacement_km,Time_Since_SparkPlug_Replacement_km,Need_Maintenance,Failure_Type,Remaining_Useful_Life_km
0,FFV2-000001,2023-07-04,Truck,10,2876,Standard,Coastal,22.3,73.3,394.0,...,Pass,151.0,1.47,11.70,19.0,140675.0,19822.0,Yes,Catalytic Converter,5383.0
1,FFV2-000002,2024-08-21,SUV,8,1935,Retrofit-Upgraded,Arid,22.7,29.3,629.0,...,Pass,140.0,1.74,11.79,93.0,158999.0,13537.0,Yes,Electrical,4120.0
2,FFV2-000003,2024-02-28,Truck,3,2964,Ethanol-Compatible (Tier-2/3),Arid,35.5,21.6,1538.0,...,Pass,96.0,1.47,12.10,221.0,51807.0,22730.0,No,No Failure,15566.0
3,FFV2-000004,2024-02-09,SUV,10,1945,Standard,Humid,23.8,78.2,391.0,...,Pass,129.0,1.67,NaN,23.0,121717.0,50980.0,Yes,Fuel System,3256.0
4,FFV2-000005,2024-05-16,Car,10,1125,Standard,Arid,40.5,28.0,NaN,...,Pass,160.0,1.86,11.80,195.0,3064.0,84.0,Yes,Injector,1037.0

================================================================================
3. DATASET INFORMATION
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 56 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Vehicle_ID                           120000 non-null  object
 1   Timestamp                            120000 non-null  object
 2   Vehicle_Model                        120000 non-null  object
 3   Vehicle_Age_years                    120000 non-null  int64
 4   Engine_Size_cc                       120000 non-null  int64
 5   Fuel_System_Material_Compatibility   120000 non-null  object
 6   Climate_Region                       120000 non-null  object
 7   Ambient_Temperature_C                117547 non-null  float64
 8   Humidity_Pct                         115229 non-null  float64
 9   Altitude_m                           112788 non-null  float64
 10  Ethanol_Content_Pct                  120000 non-null  float64
 11  Fuel_Vapor_Pressure_Class            114060 non-null  object
 12  Fuel_Consumption_Rate_L_100km        117564 non-null  float64
 13  Fuel_Rail_Pressure_kPa               117536 non-null  float64
 14  Injector_Duty_Cycle_Pct              117535 non-null  float64
 15  Fuel_Water_Contamination_ppm         109012 non-null  float64
 16  LTFT_Pct                             117572 non-null  float64
 17  STFT_Pct                             117629 non-null  float64
 18  Oil_Pressure_psi                     117561 non-null  float64
 19  Oil_Temperature_C                    117591 non-null  float64
 20  Coolant_Temperature_C                117564 non-null  float64
 21  Vibration_Level_mm_s                 117619 non-null  float64
 22  Knock_Sensor_Level                   117594 non-null  float64
 23  Exhaust_Gas_Temperature_C            117554 non-null  float64
 24  RPM_Avg                              117579 non-null  float64
 25  Idle_RPM_StdDev                      117579 non-null  float64
 26  AFR_Lambda                           117619 non-null  float64
 27  MAP_kPa                              117583 non-null  float64
 28  Engine_Load_Pct                      120000 non-null  float64
 29  Compression_Ratio_Change_Pct         107894 non-null  float64
 30  Total_Mileage_km                     120000 non-null  int64
 31  Engine_Run_Hours                     117585 non-null  float64
 32  Idle_Time_Pct                        117640 non-null  float64
 33  Avg_Load_Pct                         117598 non-null  float64
 34  Towing_Flag                          120000 non-null  bool
 35  Driving_Pattern                      120000 non-null  object
 36  Harsh_Event_Count_per_trip           113982 non-null  float64
 37  Blend_Switch_Frequency_per_month     117565 non-null  float64
 38  Avg_Trip_Length_km                   113886 non-null  float64
 39  Injector_Flow_Drift_Pct              116371 non-null  float64
 40  Misfire_Count_per_1000rev            116252 non-null  float64
 41  Spark_Plug_Wear_mm                   116527 non-null  float64
 42  Fuel_Pump_Current_A                  116500 non-null  float64
 43  Fuel_Pump_Pressure_Decay_kPa_min     116420 non-null  float64
 44  Catalytic_Converter_Efficiency_Pct   116423 non-null  float64
 45  Fuel_System_Corrosion_Score          116389 non-null  float64
 46  Fuel_Line_Seal_Condition             116347 non-null  object
 47  O2_Sensor_Response_ms                110411 non-null  float64
 48  Cold_Start_Duration_s                116363 non-null  float64
 49  Cranking_Voltage_V                   116492 non-null  float64
 50  Time_Since_Last_Service_days         117525 non-null  float64
 51  Time_Since_Injector_Replacement_km   116437 non-null  float64
 52  Time_Since_SparkPlug_Replacement_km  116452 non-null  float64
 53  Need_Maintenance                     120000 non-null  object
 54  Failure_Type                         120000 non-null  object
 55  Remaining_Useful_Life_km             120000 non-null  float64
dtypes: bool(1), float64(42), int64(3), object(10)
memory usage: 50.5+ MB

================================================================================
4. DATA TYPES
================================================================================

                                    Data Type
Vehicle_ID                             object
Timestamp                              object
Vehicle_Model                          object
Vehicle_Age_years                       int64
Engine_Size_cc                          int64
Fuel_System_Material_Compatibility     object
Climate_Region                         object
Ambient_Temperature_C                 float64
Humidity_Pct                          float64
Altitude_m                            float64
Ethanol_Content_Pct                   float64
Fuel_Vapor_Pressure_Class              object
Fuel_Consumption_Rate_L_100km         float64
Fuel_Rail_Pressure_kPa                float64
Injector_Duty_Cycle_Pct               float64
Fuel_Water_Contamination_ppm          float64
LTFT_Pct                              float64
STFT_Pct                              float64
Oil_Pressure_psi                      float64
Oil_Temperature_C                     float64
Coolant_Temperature_C                 float64
Vibration_Level_mm_s                  float64
Knock_Sensor_Level                    float64
Exhaust_Gas_Temperature_C             float64
RPM_Avg                               float64
Idle_RPM_StdDev                       float64
AFR_Lambda                            float64
MAP_kPa                               float64
Engine_Load_Pct                       float64
Compression_Ratio_Change_Pct          float64
Total_Mileage_km                        int64
Engine_Run_Hours                      float64
Idle_Time_Pct                         float64
Avg_Load_Pct                          float64
Towing_Flag                              bool
Driving_Pattern                        object
Harsh_Event_Count_per_trip            float64
Blend_Switch_Frequency_per_month      float64
Avg_Trip_Length_km                    float64
Injector_Flow_Drift_Pct               float64
Misfire_Count_per_1000rev             float64
Spark_Plug_Wear_mm                    float64
Fuel_Pump_Current_A                   float64
Fuel_Pump_Pressure_Decay_kPa_min      float64
Catalytic_Converter_Efficiency_Pct    float64
Fuel_System_Corrosion_Score           float64
Fuel_Line_Seal_Condition               object
O2_Sensor_Response_ms                 float64
Cold_Start_Duration_s                 float64
Cranking_Voltage_V                    float64
Time_Since_Last_Service_days          float64
Time_Since_Injector_Replacement_km    float64
Time_Since_SparkPlug_Replacement_km   float64
Need_Maintenance                       object
Failure_Type                           object
Remaining_Useful_Life_km              float64

================================================================================
5. MISSING VALUE ANALYSIS
================================================================================

                                     Missing Values  Missing Percentage (%)
Compression_Ratio_Change_Pct                  12106                   10.09
Fuel_Water_Contamination_ppm                  10988                    9.16
O2_Sensor_Response_ms                          9589                    7.99
Altitude_m                                     7212                    6.01
Avg_Trip_Length_km                             6114                    5.10
Harsh_Event_Count_per_trip                     6018                    5.01
Fuel_Vapor_Pressure_Class                      5940                    4.95
Humidity_Pct                                   4771                    3.98
Misfire_Count_per_1000rev                      3748                    3.12
Fuel_Line_Seal_Condition                       3653                    3.04
Cold_Start_Duration_s                          3637                    3.03
Injector_Flow_Drift_Pct                        3629                    3.02
Fuel_System_Corrosion_Score                    3611                    3.01
Fuel_Pump_Pressure_Decay_kPa_min               3580                    2.98
Catalytic_Converter_Efficiency_Pct             3577                    2.98
Time_Since_Injector_Replacement_km             3563                    2.97
Time_Since_SparkPlug_Replacement_km            3548                    2.96
Cranking_Voltage_V                             3508                    2.92
Fuel_Pump_Current_A                            3500                    2.92
Spark_Plug_Wear_mm                             3473                    2.89
Time_Since_Last_Service_days                   2475                    2.06
Injector_Duty_Cycle_Pct                        2465                    2.05
Fuel_Rail_Pressure_kPa                         2464                    2.05
Ambient_Temperature_C                          2453                    2.04
Exhaust_Gas_Temperature_C                      2446                    2.04
Blend_Switch_Frequency_per_month               2435                    2.03
Fuel_Consumption_Rate_L_100km                  2436                    2.03
Oil_Pressure_psi                               2439                    2.03
Coolant_Temperature_C                          2436                    2.03
LTFT_Pct                                       2428                    2.02
Idle_RPM_StdDev                                2421                    2.02
RPM_Avg                                        2421                    2.02
Oil_Temperature_C                              2409                    2.01
MAP_kPa                                        2417                    2.01
Engine_Run_Hours                               2415                    2.01
Avg_Load_Pct                                   2402                    2.00
Knock_Sensor_Level                             2406                    2.00
STFT_Pct                                       2371                    1.98
AFR_Lambda                                     2381                    1.98
Vibration_Level_mm_s                           2381                    1.98
Idle_Time_Pct                                  2360                    1.97

================================================================================
6. DUPLICATE ANALYSIS
================================================================================
Duplicate Rows : 0

================================================================================
7. NUMERICAL FEATURE SUMMARY
================================================================================

,Vehicle_Age_years,Engine_Size_cc,Ambient_Temperature_C,Humidity_Pct,Altitude_m,Ethanol_Content_Pct,Fuel_Consumption_Rate_L_100km,Fuel_Rail_Pressure_kPa,Injector_Duty_Cycle_Pct,Fuel_Water_Contamination_ppm,...,Fuel_Pump_Pressure_Decay_kPa_min,Catalytic_Converter_Efficiency_Pct,Fuel_System_Corrosion_Score,O2_Sensor_Response_ms,Cold_Start_Duration_s,Cranking_Voltage_V,Time_Since_Last_Service_days,Time_Since_Injector_Replacement_km,Time_Since_SparkPlug_Replacement_km,Remaining_Useful_Life_km
count,120000.000000,120000.000000,117547.000000,115229.000000,112788.000000,120000.000000,117564.000000,117536.000000,117535.000000,109012.000000,...,116420.000000,116423.000000,116389.000000,110411.000000,116363.000000,116492.000000,117525.000000,116437.000000,116452.000000,120000.000000
mean,5.519483,1995.969308,23.937502,55.620879,497.905681,28.399925,9.131550,338.826740,41.052453,268.698744,...,13.328850,77.659826,1.843683,118.983715,1.641021,12.060633,115.404697,78086.529860,18067.101535,10092.204903
std,2.857716,512.761239,8.517607,22.873107,486.535512,15.161602,1.278309,23.598878,7.420435,82.962168,...,5.612706,11.179504,0.671463,21.887356,0.403338,0.231667,66.994487,55284.586876,12724.986208,4791.888194
min,1.000000,1000.000000,-1.200000,5.000000,0.000000,0.300000,5.810000,80.195948,19.200000,0.000000,...,0.000000,51.500000,1.000000,62.000000,0.500000,11.320000,0.000000,8.000000,0.000000,200.000000
25%,3.000000,1632.000000,18.580000,42.400000,191.967500,16.580000,8.220000,331.280000,35.670000,211.540000,...,9.160000,68.500000,1.020000,101.390000,1.370000,11.900000,57.730000,31380.660000,7833.677500,6047.270000
50%,6.000000,1905.000000,24.790000,60.350000,368.180000,26.670000,8.950000,340.790000,40.590000,267.280000,...,12.750000,77.740000,1.990000,118.790000,1.610000,12.060000,115.610000,71546.500000,15829.875000,10399.620000
75%,8.000000,2249.000000,29.670000,71.820000,548.390000,38.540000,9.850000,349.570000,45.970000,324.470000,...,17.050000,87.170000,2.020000,136.240000,1.870000,12.230000,172.650000,114440.830000,26147.515000,14293.355000
max,10.000000,4000.000000,47.800000,100.000000,2200.000000,80.000000,14.840000,388.800000,69.900000,565.000000,...,34.300000,99.500000,5.000000,180.000000,4.390000,12.830000,234.000000,352089.000000,59174.000000,20000.000000

================================================================================
8. TARGET VARIABLE ANALYSIS
================================================================================

Need_Maintenance Distribution

Need_Maintenance
No     60833
Yes    59167
Name: count, dtype: int64

Percentage Distribution

Need_Maintenance
No     50.69
Yes    49.31
Name: proportion, dtype: float64

Failure_Type Distribution

Failure_Type
No Failure             60833
Fuel System            10071
Cooling System          9685
Electrical              8615
Ignition                8501
Injector                8069
Lubrication             7341
Catalytic Converter     6885
Name: count, dtype: int64

Remaining_Useful_Life_km Summary

count    120000.000000
mean      10092.204903
std        4791.888194
min         200.000000
25%        6047.270000
50%       10399.620000
75%       14293.355000
max       20000.000000
Name: Remaining_Useful_Life_km, dtype: float64

================================================================================
9. DATASET QUALITY SUMMARY
================================================================================
Total Features          : 56
Total Records           : 120,000
Missing Values          : 156,626
Duplicate Rows          : 0
Numeric Features        : 45
Categorical Features    : 11

================================================================================
10. OBSERVATIONS
================================================================================
• Dataset loaded successfully.
• Dataset structure verified.
• Data types inspected.
• Missing values identified.
• Duplicate rows checked.
• Target variables verified.
• Dataset remains unchanged.
• Dataset is ready for Stage 2 (Exploratory Data Analysis).